drop table if exists web_navigation_user;
create table web_navigation_user
(
    uid         bigint primary key generated by default as identity (start with 10000),
    nick_name   varchar(100) not null,
    create_time timestamp with time zone default (now() AT TIME ZONE 'PRC')
);

drop table if exists web_navigation_config;
create table web_navigation_config
(
    id          bigint primary key generated by default as identity,
    uid         bigint not null,
    config_json jsonb  not null          default '[]'::jsonb,
    update_time timestamp with time zone default (now() AT TIME ZONE 'PRC')
);

alter table web_navigation_user disable row level security;
alter table web_navigation_config disable row level security;
